# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Wagner group
tagline:             'Many particle simulations of condensed matter'
description:         ''
url:                 http://wagner.physics.illinois.edu
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Lucas Wagner
#  url:               https://twitter.com/mdo
  email:             lkwagner@illinois.edu

# Custom vars
version:             1.0.0
